#!/usr/bin/expect

set timeout 100

set password [lindex $argv 0]
set output [lindex $argv 1]
set input [lindex $argv 2]

spawn crypt.py --decrypt --output-file $output $input
expect "enter passphrase: " { send "$password\r" }
interact
